environment:
  matrix:
    - nodejs_version: '20'
before_test:
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - PATH=C:\Program Files\PostgreSQL\10\bin\;%PATH%
  - createdb testdb
services:
  - postgresql101
install:
  - npm
test_script:
  - npm run test
build: off
